In [1]:
# Dependencies
import pandas as pd
import plotly.express as plt
import os
import statsmodels.api as sm

In [5]:
# Import dataset from file
bikecounts_file = os.path.join('../','Resources', 'bikecounts.csv')
bikecounts_df = pd.read_csv(bikecounts_file)
bikecounts_df['Day'] = pd.to_datetime(bikecounts_df['Day'])

# Remove the index column
bikecounts_df.drop(columns=['Unnamed: 0'], inplace=True)

# Calculate the median temperature
bikecounts_df['Median Temp (°F)']=(bikecounts_df['High Temp (°F)']+bikecounts_df['Low Temp (°F)'])/2

bikecounts_df.head(10)

,Date,Day,High Temp (°F),Low Temp (°F),Precipitation,Brooklyn Bridge,Manhattan Bridge,Williamsburg Bridge,Queensboro Bridge,Total,Median Temp (°F)
0,2016-04-01,2016-04-01,78.1,66.0,0.01,1704.0,3126,4115.0,2552.0,11497,72.05
1,2016-04-02,2016-04-02,55.0,48.9,0.15,827.0,1646,2565.0,1884.0,6922,51.95
2,2016-04-03,2016-04-03,39.9,34.0,0.09,526.0,1232,1695.0,1306.0,4759,36.95
3,2016-04-04,2016-04-04,44.1,33.1,0.47 (S),521.0,1067,1440.0,1307.0,4335,38.60
4,2016-04-05,2016-04-05,42.1,26.1,0,1416.0,2617,3081.0,2357.0,9471,34.10
5,2016-04-06,2016-04-06,45.0,30.0,0,1885.0,3329,3856.0,2849.0,11919,37.50
6,2016-04-07,2016-04-07,57.0,53.1,0.09,1276.0,2581,3282.0,2457.0,9596,55.05
7,2016-04-08,2016-04-08,46.9,44.1,0.01,1982.0,3455,4113.0,3194.0,12744,45.50
8,2016-04-09,2016-04-09,43.0,37.9,0.09,504.0,997,1507.0,1502.0,4510,40.45
9,2016-04-10,2016-04-10,48.9,30.9,0,1447.0,2387,3132.0,2160.0,9126,39.90

#Hypothesis
There is a positive correlation between temperature and the number of bikes crossing the brooklyn bridge.

In [7]:
independent_variables=bikecounts_df[['Median Temp (°F)']]
dependent_value=bikecounts_df['Brooklyn Bridge']
X=sm.add_constant(independent_variables)
regression_model=sm.OLS(dependent_value,X)
results=regression_model.fit()

<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x0000018CDE53A7C0>

In [8]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Brooklyn Bridge   R-squared:                       0.412
Model:                            OLS   Adj. R-squared:                  0.391
Method:                 Least Squares   F-statistic:                     19.60
Date:                Fri, 05 Nov 2021   Prob (F-statistic):           0.000132
Time:                        21:34:23   Log-Likelihood:                -241.20
No. Observations:                  30   AIC:                             486.4
Df Residuals:                      28   BIC:                             489.2
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const            -1136.4314    782.299     -1.453      0.157   -2738.898     466.036
Median Temp (°F)    63.6687     14.381      4.427      0.000      34.211      93.126
==============================================================================
Omnibus:                        3.244   Durbin-Watson:                   1.274
Prob(Omnibus):                  0.198   Jarque-Bera (JB):                2.736
Skew:                          -0.640   Prob(JB):                        0.255
Kurtosis:                       2.258   Cond. No.                         300.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [9]:
results.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                    Results: Ordinary least squares
=======================================================================
Model:                OLS               Adj. R-squared:      0.391
Dependent Variable:   Brooklyn Bridge   AIC:                 486.4023
Date:                 2021-11-05 21:34  BIC:                 489.2047
No. Observations:     30                Log-Likelihood:      -241.20
Df Model:             1                 F-statistic:         19.60
Df Residuals:         28                Prob (F-statistic):  0.000132
R-squared:            0.412             Scale:               6.0392e+05
-----------------------------------------------------------------------
                   Coef.    Std.Err.    t    P>|t|    [0.025    0.975]
-----------------------------------------------------------------------
const            -1136.4314 782.2991 -1.4527 0.1574 -2738.8985 466.0356
Median Temp (°F)    63.6687  14.3808  4.4273 0.0001    34.2110  93.1265
-----------------------------------------------------------------------
Omnibus:                 3.244          Durbin-Watson:            1.274
Prob(Omnibus):           0.198          Jarque-Bera (JB):         2.736
Skew:                    -0.640         Prob(JB):                 0.255
Kurtosis:                2.258          Condition No.:            300
=======================================================================

"""

##Conclusion
The P-value for Median Temperature is 0.0001 we find significant evidence to reject the null hypothesis. There is a positive correlation between the number of bikes crossing the brooklyn bridge and the median temperature.